apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors
spec:
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
      - name: doctors
        image: devteam18/doctors-app
        ports:
        - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
spec:
  selector:
    app: doctor-service
  ports:
  - port: 8002
    targetPort: 8002

